name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4

      - name: Build
        run: npm run build
